site_name: FiveOrbs Cli
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: fiveorbs
repo_url: https://github.com/fiveorb/cli
extra:
    project: FiveOrbs Cli
plugins:
    - search
    - macros:
        module_name: docs/main
