site_name: Duon Cli
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: duon
repo_url: https://github.com/duoncode/cli
extra:
    project: Duon Cli
plugins:
    - search
    - macros:
        module_name: docs/main
