name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
      - name: Setup PHP extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: curl, xml, zip

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages with composer
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-text --coverage-filter=src --path-coverage

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github --shepherd

      - name: Run PHP Code Sniffer
        run: ./vendor/bin/phpcs -q --report=checkstyle src tests | ./vendor/bin/cs2pr

  docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-duon
      - run: mkdocs gh-deploy --force
